### create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "id": "3",
  "brand": "keyboard mecanical",
  "description": "keyboard mecanical berkualitas tinggi",
  "price": 250000,
  "promo": 240000,
  "category": "accesories electronic",
  "image": ["https://images.pexels.com/photos/24181863/pexels-photo-24181863/free-photo-of-top-view-of-a-keyboard-on-a-gray-background.jpeg?auto=compress&cs=tinysrgb&w=600"]
}

### read all
GET http://localhost:3000/products

### read by id
GET http://localhost:3000/products/1

### update (Update) by id
PUT http://localhost:3000/products/1
Content-Type: application/json

{
  "id": "1",
  "brand": "headset robot",
  "description": "headset berkualitas tinggi dengan harga terjangkau",
  "price": 90000,
  "promo": 85000,
  "category": "accesories electronic",
  "image": ["https://example.com/image-updated.jpg"]
}

### delete product by id
DELETE http://localhost:3000/products/1

### get category
POST http://localhost:3000/category
Content-Type: application/json

{
  "id" : "5",
  "category" : "komputer"
}